# Background and foreground colors
background = #0d0b09
foreground = #d7d3d0

# Standard colors
palette = 0=#0d0b09
palette = 1=#dc4506
palette = 2=#d57059
palette = 3=#ffb000
palette = 4=#7d7969
palette = 5=#f06400
palette = 6=#b7a993
palette = 7=#d7d3d0

# Bright colors
palette = 8=#827c77
palette = 9=#f78f00
palette = 10=#ffaa71
palette = 11=#ffdb74
palette = 12=#a19186
palette = 13=#ffb7a7
palette = 14=#f5e1d8
palette = 15=#d7d3d0
selection-foreground = #d7d3d0
selection-background = #2f2722
