$color = rgba(13, 11, 9, 1)
$inner_color = rgba(13, 11, 9, 0.66)
$outer_color = rgba(255, 90, 54, 1)
$font_color = rgba(215, 211, 208, 1)
$placeholder_color = rgba(215, 211, 208, 0.7)
$check_color = rgba(255, 176, 0, 1)
