background            #0d0b09
foreground            #d7d3d0

# black
color0  #0d0b09
color8  #827c77

# red
color1  #dc4506
color9  #f78f00

# green
color2  #d57059
color10 #ffaa71

# yellow
color3  #ffb000
color11 #ffdb74

# blue
color4  #7d7969
color12 #a19186

# magenta
color5  #f06400
color13 #ffb7a7

#cyan
color6  #b7a993
color14 #f5e1d8

#white
color7  #d7d3d0
color15 #d7d3d0
selection_foreground #d7d3d0
selection_background #2f2722
