# Background and foreground colors
background = #faf6f3
foreground = #221c18

# Standard colors
palette = 0=#faf6f3
palette = 1=#720000
palette = 2=#7e2913
palette = 3=#8b6000
palette = 4=#3c342b
palette = 5=#ad4e44
palette = 6=#564241
palette = 7=#221c18

# Bright colors
palette = 8=#8c857f
palette = 9=#c1624e
palette = 10=#cf794b
palette = 11=#af7c00
palette = 12=#827271
palette = 13=#c3746f
palette = 14=#6b5d58
palette = 15=#221c18
selection-foreground = #221c18
selection-background = #e6ded8
