$color = rgba(250, 246, 243, 1)
$inner_color = rgba(250, 246, 243, 0.66)
$outer_color = rgba(255, 90, 54, 1)
$font_color = rgba(34, 28, 24, 1)
$placeholder_color = rgba(34, 28, 24, 0.7)
$check_color = rgba(255, 176, 0, 1)
