background            #faf6f3
foreground            #221c18

# black
color0  #faf6f3
color8  #8c857f

# red
color1  #720000
color9  #c1624e

# green
color2  #7e2913
color10 #cf794b

# yellow
color3  #8b6000
color11 #af7c00

# blue
color4  #3c342b
color12 #827271

# magenta
color5  #ad4e44
color13 #c3746f

#cyan
color6  #564241
color14 #6b5d58

#white
color7  #221c18
color15 #221c18
selection_foreground #221c18
selection_background #e6ded8
